export const ADD_STICK = "ADD_STICK";
export const ADD_BUTTON = "ADD_BUTTON";
export const ADD_GAMEPAD = "ADD_GAMEPAD";
export const EDIT_GAMEPAD = "EDIT_GAMEPAD";
export const LOCK_LANDSCAPE = "LOCK_LANDSCAPE";
export const UNLOCK_ORIENTATION = "UNLOCK_ORIENTATIO";